version: '3.8'

services:
  db:
    image: postgres:15
    container_name: task-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-net

  task-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - task-net
    environment:
      CONFIG_PATH: /app/config.yaml
    volumes:
      - ./config/config.yaml:/app/config.yaml 

volumes:
  postgres-data:

networks:
  task-net:
